include isManual for connecting to protocol substrate node that was m…
webb-tools/relayer pull request #133
Opened 2022-04-12 11:54 UTC by dharjeezy

connect to protocol substrate node that was run manually

2022-04-12 17:33 UTC, shekohex requested changes
Looking good!
just a few changes here.

2022-04-12 17:33 UTC, shekohex commented on tests/lib/localProtocolSubstrate.ts
> +    console.log(`ports are ${opts.ports}`);
Remove this:
```suggestion
```

2022-04-13 08:38 UTC, dharjeezy commented on tests/lib/localProtocolSubstrate.ts
> +    console.log(`ports are ${opts.ports}`);
So, I already removed it.

2022-04-13 08:49 UTC, shekohex requested changes
Looks good so far! just a few more comments

2022-04-13 08:49 UTC, shekohex commented on tests/test/subTransactionRelayer.test.ts
> +    expect(balanceAfterWithdraw > initialBalance).true;
Try this instead, it is better in terms when the case fails it will print both values for you:
```suggestion
    expect(balanceAfterWithdraw).to.be.gt(initialBalance);
```

2022-04-13 08:49 UTC, shekohex commented on tests/test/subTransactionRelayer.test.ts
> +    }
Are these are being used? and where?

2022-04-13 08:52 UTC, dharjeezy commented on tests/test/subTransactionRelayer.test.ts
> +    }
These are configurations for the nodes i sprung up manually.

2022-04-13 08:52 UTC, dharjeezy commented on tests/test/subTransactionRelayer.test.ts
> +    expect(balanceAfterWithdraw > initialBalance).true;
Alright. Thanks

2022-04-13 08:55 UTC, shekohex commented on tests/test/subTransactionRelayer.test.ts
>          };
You see, usage mode here are still not using the manual starting, am I right?

2022-04-13 08:55 UTC, shekohex commented on tests/test/subTransactionRelayer.test.ts
> +    }
But where these variables are being used? can't find a usage for any of them

2022-04-13 10:19 UTC, dharjeezy commented on tests/test/subTransactionRelayer.test.ts
> +    expect(balanceAfterWithdraw > initialBalance).true;
Hello @shekohex i had to change it back to this `expect(balanceAfterWithdraw > initialBalance).true;`
because the test fails, `balanceAfterWithdraw` and ` initialBalance` are both BigInt and not number or date, therefore `expect(balanceAfterWithdraw).to.be.gt(initialBalance);` fails to assert

2022-04-13 10:20 UTC, dharjeezy commented on tests/test/subTransactionRelayer.test.ts
> +    }
Alright. I will remove them then

2022-04-13 10:20 UTC, dharjeezy commented on tests/test/subTransactionRelayer.test.ts
>          };
yh... i will remove the the alice and bob manual ports

2022-04-13 10:34 UTC, shekohex approved these changes
Looks good!

2022-04-13 11:17 UTC, merged