Signing Backends
webb-tools/relayer pull request #142
Opened 2022-04-13 12:36 UTC by shekohex

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Closes #120 

## What is the new behavior?

> TODO: add example of the new configs here.

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

Config Changes.

## Other information

See Spec. #120

2022-04-13 20:18 UTC, dutterbutter approved these changes
LGTM! 

Can we just add a row to the config table in the `README.md` for the `signing-backend` field?

2022-04-13 20:18 UTC, dutterbutter commented on src/events_watcher/signing_backend/mod.rs
> +pub use mocked::*;
It would be good to document these for the implementation docs.

2022-04-14 07:44 UTC, drewstone requested changes
What about calling this the ProposalSigningBackend?

I'm thinking about when we will integrate signing of txes for other chains and whether this name can be confused for those signing backends. Thoughts?

2022-04-14 07:44 UTC, drewstone commented on src/config.rs
> +    /// The type of the Siging backend used for signing proposals.
Spelling

2022-04-14 08:50 UTC, dharjeezy commented on tests/lib/localTestnet.ts
> +      chainId: this.underlayingChainId,
should be underlyingChainId, yh?

2022-04-14 08:51 UTC, dharjeezy commented on tests/lib/localTestnet.ts
> +  public get underlayingChainId(): number {
should be underlyingChainId

2022-04-14 14:30 UTC, shekohex commented on src/config.rs
> +    /// The type of the Siging backend used for signing proposals.
Fixed.

2022-04-14 15:47 UTC, drewstone approved these changes
LGTM

2022-04-14 15:48 UTC, merged