Changes to poll blocks instead of stream, test fixes
webb-tools/relayer pull request #15
Opened 2021-08-18 20:12 UTC by nepoche

2021-08-18 22:56 UTC, nepoche commented on src/leaf_cache.rs
> +        Ok(())
What would be the best way to resolve these clippy issues?

2021-08-19 12:21 UTC, shekohex commented on src/leaf_cache.rs
> +        Ok(())
Just remove the `Ok(())` as there is no way for this loop to stop itself, other than an error happens, and in this case, the whole task will start over again.

2021-08-19 15:40 UTC, shekohex commented
it sounds that you need to run `cargo fmt` to fix any formatting issues.

2021-08-20 02:50 UTC, drewstone commented on src/leaf_cache.rs
> +            tokio::time::sleep(Duration::from_secs(30)).await;
A smaller interval only makes sense if the block time of that chain is small. For Ethereum, as an example, 6 seconds doesn't make much sense since blocks arrive every 12-15 seconds. 

Afaik we should abstract this parameter away into configuration based on the chain settings. Polling should happen as a function of the chain we're polling against and therefore the block time of that chain.

2021-08-20 02:52 UTC, drewstone requested changes

2021-08-20 02:52 UTC, drewstone commented on tests/scripts/cronTaskManager.ts
> +    cron.schedule(`${i} */10 * * * *`, async () => {
Can we add comments as to what time this is?

2021-08-20 11:04 UTC, shekohex commented on src/leaf_cache.rs
> +            tokio::time::sleep(Duration::from_secs(30)).await;
I agree we should add this into the configuration of the chain.

2021-08-20 12:36 UTC, nepoche commented on src/leaf_cache.rs
> +            tokio::time::sleep(Duration::from_secs(30)).await;
I added a `polling_interval_ms` parameter on the chain

2021-08-20 13:10 UTC, shekohex approved these changes

2021-08-20 18:25 UTC, merged