Salman substrate event watcher
webb-tools/relayer pull request #164
Opened 2022-04-22 18:36 UTC by salman01zp

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-04-22 19:59 UTC, dutterbutter commented
@salman01zp please resolve conflicts

2022-04-25 13:08 UTC, shekohex commented on tests/test/substrate/anchorTransactionRelayer.test.ts
> +    await sleep(10000);
Please don't use `sleep` to wait for something to start, it will be different between the test env. Instead, use `waitForEvent` and define some event. usually, we wait until the DKG public key is submitted (in the case of the DKG) and for protocol-substrate, you can wait until the first block number or even send a dummy transaction like `api.tx.system.remark('0x00')` to just make sure the API is ready.

2022-04-26 03:49 UTC, salman01zp commented on tests/test/substrate/anchorTransactionRelayer.test.ts
> +    await sleep(10000);
Thanks. I am using api.isReady now, which ensures it is ready and connected.

2022-04-26 09:32 UTC, shekohex requested changes
Looks good! 

just a few comments.

2022-04-26 09:32 UTC, shekohex commented on src/events_watcher/substrate/anchor_leaves_watcher.rs
> +    const TAG: &'static str = "Substrate leaves Watcher";
```suggestion
    const TAG: &'static str = "Substrate Anchor leaves Watcher";
```

2022-04-26 09:32 UTC, shekohex commented on src/store/mod.rs
>                  // a bit hacky, but we don't have a way to get the address from the node name
```suggestion
                // a bit hacky, but we don't have a way to get the address from the tree id
```

2022-04-26 09:32 UTC, shekohex commented on tests/test/utils/util.ts
> +}
Please add types, and comments if possible.

2022-04-26 09:32 UTC, shekohex commented on tests/test/substrate/anchorTransactionRelayer.test.ts
> +    const nodeName = ethAddressFromString(treeId.toString());
```suggestion
    const treeIdAddress = ethAddressFromString(treeId.toString());
```

2022-04-26 09:32 UTC, shekohex commented on tests/test/substrate/anchorTransactionRelayer.test.ts
> +    const response = await webbRelayer.getLeaves(chainIdHex, nodeName);
```suggestion
    const response = await webbRelayer.getLeaves(chainIdHex, treeIdAddress);
```

2022-04-26 09:35 UTC, shekohex commented on tests/test/utils/util.ts
> +}
Also, can we rename this file to `ethAddressFromString.ts`? I Kinda find any file named `utils` is useless and will get messy over time.

2022-04-26 12:03 UTC, shekohex commented on tests/test/utils/ethAddressFromString.ts
> +): number[] {
```suggestion
function resize<T>(
  arr: T[],
  newSize: T,
  defaultValue: T
): T[] {
```

2022-04-26 20:30 UTC, shekohex approved these changes
LGTM!

2022-04-26 21:08 UTC, merged