evm vanchor leaves watcher #160
webb-tools/relayer pull request #172
Opened 2022-05-02 15:35 UTC by salman01zp

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-05-06 12:28 UTC, drewstone commented
Need to fix CI errors before merge. Will review soon. Try merging master if this hasn't happened.

2022-05-06 15:17 UTC, shekohex requested changes
LGTM!! Good job!

A few changes and CI shall pass, and we can merge this. but if the CI starts to act randomly again we can merge in `master` for now.

2022-05-06 15:17 UTC, shekohex commented on src/service.rs
> +/// * `client` - DKG client
```suggestion
/// * `client` - EVM Chain api client
```

2022-05-06 15:17 UTC, shekohex commented on tests/lib/localTestnet.ts
> +  public async getVAnchorChainConfig(
make it private?
```suggestion
  private async getVAnchorChainConfig(
```

2022-05-06 15:17 UTC, shekohex commented on tests/lib/localTestnet.ts
> +  public async getAnchorChainConfig(
shall be private

```suggestion
  private async getAnchorChainConfig(
```

2022-05-09 13:55 UTC, shekohex approved these changes

2022-05-10 12:27 UTC, merged