vanchor governance
webb-tools/relayer pull request #211
Opened 2022-07-04 14:00 UTC by salman01zp

## Task Checklist
- [x] Implement Vanchor Watcher
- [x] Update `Protocol-substrate` to  include `vanchor-handler` in runtime. [PR](url)
- [ ] Update substrate metadata in webb-rs [PR](url)
- [ ] Add tests for Vanchor Watcher

**Reference issue to close (if applicable)**

Closes #192 

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

2022-07-05 13:23 UTC, shekohex requested changes

2022-07-05 13:23 UTC, shekohex commented on src/events_watcher/substrate/signature_bridge_watcher.rs
> +                                call = "executed_proposal_with_signature",
```suggestion
                                call = "execute_proposal_with_signature",
```

2022-07-05 13:23 UTC, shekohex commented on src/events_watcher/substrate/vanchor_watcher.rs
> +    linked_anchors: &'a [SubstrateLinkedAnchorConfig],
Why do we need this with a lifetime? why not just a clone of the that as `Vec<SubstrateLinkedAnchorConfig>`?

2022-07-05 13:23 UTC, shekohex commented on tests/lib/webbRelayer.ts
> +export function getChainIdType(chainID: number = 31337): number {
Chain Id type for? Substrate? EVM? this function name does not say what type, besides it takes a predefined default parameter.

Please make the name chain specific like `getSubstrateTypedChainId` for example.

Also, I don't think this not being used?

2022-07-05 13:23 UTC, shekohex commented on tests/lib/webbRelayer.ts
> +export function getChainIdType(chainID: number = 31337): number {
There is ResouceId somewhere in webbProposals.js that can be used to encode/create these kind of typed chainId btw. you should use them instead.

2022-07-07 20:40 UTC, drewstone approved these changes
LGTM

2022-07-07 20:41 UTC, merged