substrate tx queue
webb-tools/relayer pull request #217
Opened 2022-07-12 13:23 UTC by salman01zp

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2022-07-29 15:10 UTC, salman01zp commented
blocked by #231. Substrate tests are failing due to changes in protocol-substrate

2022-07-30 05:15 UTC, salman01zp commented
This subxt [PR](https://github.com/paritytech/subxt/pull/593) should make it possible to build, store and later submit calls more easier

2022-08-01 13:08 UTC, shekohex requested changes
Looks good, I've left few comments for improvements.

2022-08-01 13:08 UTC, shekohex commented on src/events_watcher/substrate/signature_bridge_watcher.rs
> +        };
Here is an example: 
```rs
fn encode_call_data<C: Call>(metadata: Arc<RwLock<Metadata>>, call: C) -> Vec<u8> {
    let mut bytes = Vec::new();
    let metadata = metadata.read();
    let pallet = metadata.pallet(C::PALLET)?;
    bytes.push(pallet.index());
    call.encode_to(&mut bytes);
    bytes
}
```

2022-08-01 13:08 UTC, shekohex commented on src/events_watcher/substrate/signature_bridge_watcher.rs
> +        };
Same here, using a reusable function would make sense and reduce errors.

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +                    );
```suggestion
                    tracing::trace!(
                        "Transaction call in hex : {:?}",
                        hex::encode(&call_data.encode())
                    );
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Future",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Ready",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Broadcast",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "InBlock",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Retracted",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "FinalityTimeout",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    finalized = true,
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Usurped",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Dropped",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +
```suggestion
                                    status = "Invalid",
```

2022-08-01 13:08 UTC, shekohex commented on src/tx_queue/substrate_tx_queue.rs
> +            ty = "Substrate",
```suggestion
            ty = "SUBSTRATE",
```

2022-08-01 16:31 UTC, shekohex commented on src/tx_queue/substrate/call_data.rs
> +    bytes.push(pallet.call_index::<C>()?);
Is the call index is now needed? I guess you mentioned before that the call contains already the call index?

2022-08-01 16:38 UTC, salman01zp commented on src/tx_queue/substrate/call_data.rs
> +    bytes.push(pallet.call_index::<C>()?);
yeah. I changed its type from
(This does not implement the `Call` trait, This struct on encoding includes call index )
`webb::substrate::protocol_substrate_runtime::api::runtime_types::pallet_signature_bridge::pallet::Call`

To (this struct implements Call trait)
`webb::substrate::protocol_substrate_runtime::api::signature_bridge::calls::ExecuteProposal`

2022-08-01 17:36 UTC, shekohex approved these changes
LGTM!

Good work, Salman.

2022-08-01 17:36 UTC, merged