Events Watcher API 2.0
webb-tools/relayer pull request #228
Opened 2022-07-21 16:19 UTC by shekohex

## Summary of changes
- [x] New Events Watcher API For EVM
- [ ] New Events Watcher API For Substrate

### Reference issue to close (if applicable)
- Closes #225 

-----
### Code Checklist 

- [x] Tested
- [ ] Documented

2022-07-21 17:25 UTC, drewstone requested changes
Needs fixes, I'm not confident seeing how you're handling the futures of handlers that we are matching our expectations. Can you provide more info on why you think we should `try_join_all`? Why would we want to cancel futures if one fails?

2022-07-21 17:25 UTC, drewstone commented on src/events_watcher/mod.rs
> +                        let result = futures::future::try_join_all(
Let's instead process all futures and simply retry the ones that fail some constant # of times. We should not cancel the rest of the handlers when one fails.

2022-07-21 17:25 UTC, drewstone commented on src/probe.rs
> +    MerkleTreeInsertation,
```suggestion
    MerkleTreeInsertion,
```

2022-07-21 17:25 UTC, drewstone commented on src/probe.rs
> +    MerkleTreeInsertation,
Please fix other references to this enum

2022-07-21 19:38 UTC, shekohex commented on src/probe.rs
> +    MerkleTreeInsertation,
Done.

2022-07-21 19:41 UTC, shekohex commented on src/events_watcher/mod.rs
> +                        let result = futures::future::try_join_all(
I addressed your comments here too.

2022-07-22 17:49 UTC, drewstone approved these changes

2022-07-22 17:58 UTC, salman01zp commented on src/events_watcher/evm/signature_bridge_watcher.rs
> +pub struct SignatureBridgeGovernanceOwnershipTransferredHandler;
can we rename this struct to something small?

2022-07-22 18:21 UTC, shekohex commented on src/events_watcher/evm/signature_bridge_watcher.rs
> +pub struct SignatureBridgeGovernanceOwnershipTransferredHandler;
It is more like each handler name now at least should describes what events that they are handing. But nonetheless, I'm open for a better name.

2022-07-22 18:31 UTC, salman01zp commented on src/events_watcher/evm/signature_bridge_watcher.rs
> +pub struct SignatureBridgeGovernanceOwnershipTransferredHandler;
nothing comes to mind at present. Anyways we can update later.

2022-07-22 18:33 UTC, salman01zp approved these changes
LGTM..! Great work @shekohex

2022-07-22 19:09 UTC, merged