Add the `mnemonic` type for the cosmwasm relayer
webb-tools/relayer pull request #230
Opened 2022-07-26 13:54 UTC by duguorong009

## Summary of changes
- Introduce the new type `mnemonic` for **cosmwasm relayer implementation**

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-07-27 10:38 UTC, salman01zp reviewed
LGTM..! Just one question

I think you were also going to create `CommonContractConfig` for cosmwasm [here](https://github.com/webb-tools/relayer/blob/main/src/config.rs#L343-L352) due to incompatible address type between evm and cosmwasm

2022-07-27 12:59 UTC, duguorong009 commented
> LGTM..! Just one question
> 
> I think you were also going to create `CommonContractConfig` for cosmwasm [here](https://github.com/webb-tools/relayer/blob/main/src/config.rs#L343-L352) due to incompatible address type between evm and cosmwasm

Yes, you are right @salman01zp 
I got the similar tips from @shekohex

2022-07-29 14:05 UTC, shekohex requested changes

2022-07-29 14:05 UTC, shekohex commented on src/config.rs
> +use crate::types::{mnemonic::Mnemonic, private_key::PrivateKey};
```suggestion
use crate::types::{rpc_url::RpcUrl, suri::Suri, mnemonic::Mnemonic, private_key::PrivateKey};
```

2022-07-29 14:05 UTC, shekohex commented on src/types/mnemonic.rs
> +pub struct Mnemonic(Vec<String>);
Could we use this https://docs.rs/tiny-bip39/latest/bip39/struct.Mnemonic.html#method.from_phrase or https://docs.rs/tiny-bip39/latest/bip39/struct.Mnemonic.html#method.validate for Mnemonic validation?

2022-07-29 14:05 UTC, shekohex commented on src/types/mnemonic.rs
> +                    .collect::<Vec<String>>();
Would be better to use https://docs.rs/tiny-bip39/latest/bip39/struct.Mnemonic.html#method.from_phrase instead of our custom logic here.

2022-07-29 14:05 UTC, shekohex commented on config/development/cosmwasm-localnet/terra.toml
> +# #
Not valid anymore, right? this commit is outdated.

2022-07-29 14:05 UTC, shekohex commented on config/development/cosmwasm-localnet/juno.toml
> +# #
Same here, this comment is outdated.

2022-07-29 14:20 UTC, duguorong009 commented on config/development/cosmwasm-localnet/juno.toml
> +chain-id = "1233" # "localjuno" fake value
Original plan was to use the real `chain-id` like "localjuno" and calculate the numeric value using the formula we discussed earlier.
Here, I just used the (literally) `fake` value for the development

2022-07-29 14:25 UTC, duguorong009 commented on src/types/mnemonic.rs
> +pub struct Mnemonic(Vec<String>);
One question, @shekohex 
Do you mean we don't introduce the custom type but use the existing `mnemonic` from the `tiny_bip39` crate?

2022-07-29 14:29 UTC, duguorong009 commented on src/types/mnemonic.rs
> +                    .collect::<Vec<String>>();
Ok, will follow your recommend

2022-07-29 18:18 UTC, drewstone commented on config/development/cosmwasm-localnet/juno.toml
> +chain-id = "1233" # "localjuno" fake value
Even if we are to put the hardcoded value in there let's use the actual one, not a fake value.

2022-08-01 13:12 UTC, duguorong009 commented on src/types/mnemonic.rs
> +                    .collect::<Vec<String>>();
Done https://github.com/webb-tools/relayer/pull/230/commits/cd60a5f0389f9a322c260705a7a75e7d2aa01095

2022-08-01 13:12 UTC, duguorong009 commented on src/types/mnemonic.rs
> +pub struct Mnemonic(Vec<String>);
Done https://github.com/webb-tools/relayer/pull/230/commits/cd60a5f0389f9a322c260705a7a75e7d2aa01095

2022-08-01 13:12 UTC, duguorong009 commented on config/development/cosmwasm-localnet/juno.toml
> +# #
Cleaned in https://github.com/webb-tools/relayer/pull/230/commits/5ec0574a1aeb4c16725a460905c3dbbb7df55782

2022-08-01 13:13 UTC, duguorong009 commented on config/development/cosmwasm-localnet/terra.toml
> +# #
Cleaned in https://github.com/webb-tools/relayer/pull/230/commits/5ec0574a1aeb4c16725a460905c3dbbb7df55782

2022-08-01 13:14 UTC, duguorong009 commented on config/development/cosmwasm-localnet/juno.toml
> +chain-id = "1233" # "localjuno" fake value
Updated the **fake numeric chain_id**s with **real string one**.
Will add more code for read/convert the string chain_id to numeric one.

2022-08-01 13:16 UTC, shekohex requested changes

2022-08-01 13:16 UTC, shekohex commented on src/types/mnemonic.rs
> +                )
That's good, but I guess you forgot and removed the support of the environment variables, the using of $VAR in the config here is important, since these are secrets and it is not wise to leave them hard-coded in config files like this in plain text.

2022-08-01 13:38 UTC, duguorong009 commented on src/types/mnemonic.rs
> +                )
Thanks @shekohex 
Done https://github.com/webb-tools/relayer/pull/230/commits/db5d8f6232b920fa95f1c6cd79af2d7e33d6b728

2022-08-01 14:39 UTC, shekohex requested changes

2022-08-01 14:39 UTC, shekohex commented on src/types/mnemonic.rs
> +                }
Here is a better way to write this block:
```suggestion
                let str_value = if value.starts_with("0x") {
                    // hex value
                    return Err(serde::de::Error::custom(format!(
                        "got {} but expected a 12/24 word list ",
                        value
                    )));
                } else if value.starts_with('>') {
                    todo!("Implement command execution to extract the mnemonic")
                } else if value.starts_with('$') {
                    // env
                    let var = value.strip_prefix('$').unwrap_or(value);
                    tracing::trace!("Reading {} from env", var);
                    std::env::var(var).map_err(|e| {
                        serde::de::Error::custom(format!(
                            "error while loading this env {}: {}",
                            var, e,
                        ))
                    })?
                } else {
                    value.to_string()
                };
```

2022-08-01 19:25 UTC, merged