Extend handle_event with LogMeta
webb-tools/relayer pull request #26
Opened 2021-09-21 17:56 UTC by nepoche

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

When a client queries a relayer for the leaves, there is no way to know for which point in time this leaf history is valid.

Issue Number: N/A

## What is the new behavior?
When updates to the LeafCache are made, the relayer also stores the block number where the deposit occurred.

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2021-09-21 18:24 UTC, drewstone requested changes
Thoughts on making the methods more verbose? Optionally, I think this can be more clearly documented. It's not immediately clear that `deposit_info` is a block number. Be more explicit.

2021-09-21 18:24 UTC, drewstone commented on src/store/mem.rs
> +    fn get_last_deposit(
can we call this `get_last_deposit_blocknumber`?

2021-09-23 10:32 UTC, shekohex requested changes
Looks good to me, just a few changes to be more consistent about the API.

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/mod.rs
> +        log: contract::LogMeta,
I would highly recommend this to be changed to be a tuple of (event, log), instead of two separate parameters.
```suggestion
        (event, log): (Self::Events, contract::LogMeta)
```
That's better and akin to how ethers-rs API.

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/mod.rs
> +                        .handle_event(store.clone(), &contract, event, log.clone())
```suggestion
                        .handle_event(store.clone(), &contract, (event, log))
```

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/anchor_leaves_watcher.rs
> +                // retrieve block metadata from the log
this comment is somehow not correct, right? you are saving the last deposit block number, but here it says "retrieve"

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/anchor_leaves_watcher.rs
> +        log: LogMeta,
```suggestion
        (event, log): (Self::Events, LogMeta)
```

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/anchor2_watcher.rs
> +        _log: LogMeta,
```suggestion
        (event, _): (Self::Events, LogMeta)
```

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/anchor2_watcher.rs
> +        _log: LogMeta,
```suggestion
        (event, _): (Self::Events, LogMeta)
```

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +        _log: LogMeta,
```suggestion
        (event, _): (Self::Events, LogMeta)
```

2021-09-23 10:32 UTC, shekohex commented on src/events_watcher/anchor_leaves_watcher.rs
> +                store.insert_last_deposit(contract.address(), log.block_number)?;
```suggestion
                store.set_last_deposit_block_number(contract.address(), log.block_number)?;
```

2021-09-23 10:32 UTC, shekohex commented on src/handler.rs
> +    let last_queried_block = store.get_last_deposit(contract).unwrap();
```suggestion
    let last_queried_block = store.get_last_deposit_block_number(contract).unwrap();
```

2021-09-23 10:32 UTC, shekohex commented on src/store/mem.rs
> +    fn get_last_deposit(
```suggestion
    fn get_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/mem.rs
> +    fn insert_last_deposit(
```suggestion
    fn set_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/mod.rs
> +    fn get_last_deposit(
```suggestion
    fn get_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/mod.rs
> +    fn insert_last_deposit(
prefer using `set` as a verb for a single-valued change and use `insert` verb for lists.
```suggestion
    fn set_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/mod.rs
> +        last_deposit: types::U64,
```suggestion
        block_number: types::U64,
```

2021-09-23 10:32 UTC, shekohex commented on src/store/sled.rs
> +    fn get_last_deposit(
```suggestion
    fn get_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/sled.rs
> +        let tree = self.db.open_tree("last_deposit")?;
```suggestion
        let tree = self.db.open_tree("last_deposit_block_number")?;
```

2021-09-23 10:32 UTC, shekohex commented on src/store/sled.rs
> +    fn insert_last_deposit(
```suggestion
    fn get_last_deposit_block_number(
```

2021-09-23 10:32 UTC, shekohex commented on src/store/sled.rs
> +        last_deposit: types::U64,
```suggestion
        block_number: types::U64,
```

2021-09-23 10:32 UTC, shekohex commented on src/store/sled.rs
> +        let tree = self.db.open_tree("last_deposit")?;
```suggestion
        let tree = self.db.open_tree("last_deposit_block_number")?;
```

2021-09-24 19:31 UTC, nepoche commented
Implemented the suggested changes, and added tracing-test crate to resolve multi-threaded tracing issues.

2021-09-24 20:23 UTC, merged

2021-09-24 20:23 UTC, drewstone commented
Great work @nepoche