Bridge & Anchor2 Watcher (Phase 2)
webb-tools/relayer pull request #27
Opened 2021-09-22 18:34 UTC by shekohex

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Spec: https://www.notion.so/hicommonwealth/Spec-Bridge-Watcher-Phase-2-43cd4a382d2a417eb40953f69685279e

2021-09-22 18:46 UTC, drewstone requested changes
looks great, some small things to maybe edit unless i'm mistaken. Also, if we add TODOs, can we create tasks for them as well so we can triage in Notion?

2021-09-22 18:46 UTC, drewstone commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
We should allow for 4 bytes of data for chain IDs

2021-09-22 18:46 UTC, drewstone commented on src/service.rs
> +                    let client = Arc::new(client);
Can we combine these? `Arc::new(SignerMiddleware::new(provider, wallet))`

2021-09-22 18:46 UTC, drewstone commented on src/events_watcher/bridge_watcher.rs
> +        // TODO(@shekohex): we need a way to determine whether we should vote
Can you create a task for this and link me? These are good small tasks we should triage.

2021-09-22 18:56 UTC, drewstone commented on src/events_watcher/bridge_watcher.rs
> +                self.create_proposal(store, &wrapper.contract, data).await?;
Is there a way we can have this return the raw transaction? otherwise I would name it `create_and_send_proposal`.

2021-09-22 18:56 UTC, drewstone commented on src/events_watcher/bridge_watcher.rs
> +                self.create_proposal(store, &wrapper.contract, data).await?;
If we return raw unsigned transactions and then sign them afterwards, then we can start modularizing for the eventual TX queue.

2021-09-23 09:01 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
I guess we need to do the same on the JS side too.
here: https://github.com/webb-tools/darkwebb-solidity/blob/main/test/helpers/bridge.js#L85

2021-09-23 09:03 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
But can't change it right now, as the tests check against javascript implementation.

2021-09-23 09:05 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
We should create a spec for the `resoruceId` on notion since I get this error now when I try to create a proposal: `execution reverted: no handler for resourceID`

2021-09-23 09:13 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +                self.create_proposal(store, &wrapper.contract, data).await?;
Yes, that's the plan, we can do that once we get it to work! (a vote tx).

2021-09-23 10:13 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +        // TODO(@shekohex): we need a way to determine whether we should vote
1. https://www.notion.so/hicommonwealth/Relayer-should-Check-for-Proposal-Status-before-taking-any-action-20c890a280a54174bb54de4c1c311f46
2. https://www.notion.so/hicommonwealth/When-and-How-the-relayer-should-create-a-proposal-64d7074f227b4b0eafec66ba0ebd7f14

2021-09-23 15:57 UTC, drewstone commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
It already is correct on JS side.

2021-09-24 19:07 UTC, shekohex commented on src/events_watcher/bridge_watcher.rs
> +    let chain_id_hex = pad(&format!("{:x}", chain_id), 2);
Cool!
Fixed.

2021-09-27 12:23 UTC, merged