Dami/add metrics
webb-tools/relayer pull request #278
Opened 2022-09-27 22:34 UTC by dharjeezy

## Summary of changes
- 
Addition of metrics to the relayer

### Reference issue to close (if applicable)
- Closes #216 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-10-05 14:03 UTC, drewstone commented on src/main.rs
> +async fn initiate_metric(ctx: RelayerContext, store: SledStore) {
What in this function requires async? I don't see any awaits.

2022-10-05 14:19 UTC, dharjeezy commented on src/main.rs
> +async fn initiate_metric(ctx: RelayerContext, store: SledStore) {
This is the await being done here
https://github.com/webb-tools/relayer/pull/278/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR98

2022-10-05 14:20 UTC, dharjeezy commented on src/main.rs
> +async fn initiate_metric(ctx: RelayerContext, store: SledStore) {
> What in this function requires async? I don't see any awaits.

This is the await being done here https://github.com/webb-tools/relayer/pull/278/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR98

2022-10-06 19:46 UTC, shekohex commented on src/metric.rs
> +    pub total_number_of_data_stored_metric: GenericCounter<AtomicF64>,
This should be a [prometheus](https://docs.rs/prometheus/latest/prometheus/index.html)::[Gauge](https://docs.rs/prometheus/latest/prometheus/type.Gauge.html#) instead of a simple Counter.

2022-10-11 15:34 UTC, drewstone commented
@salman01zp the README looks wack lol, can you try and fix?

2022-10-14 05:27 UTC, drewstone commented
Need to merge master here after moving things into crates @salman01zp

2022-10-14 12:41 UTC, shekohex requested changes
Looks good! a few changes and would be good to go!

2022-10-14 12:41 UTC, shekohex commented on src/store/sled.rs
> +    pub fn get_data_stored(&self) -> u64 {
That could be a better name since the current one implies getting the whole data stored. maybe `get_data_stored_size` would work better.

2022-10-14 12:41 UTC, shekohex commented on src/handler.rs
>  /// Enumerates the supported commands for chain specific relayers
Remove that comment.

2022-10-14 12:41 UTC, shekohex commented on src/main.rs
> +    tokio::task::spawn(async move {
Store the handle of that task so you can abort it later when you shutdown. `let sled_metric_task_handle = tokio::task::spawn(...)` and later during shutdown consider using `sled_metric_task_handle.abort()` to stop it.

2022-10-14 12:41 UTC, shekohex commented on src/metric.rs
> +}
Maybe consider dropping the `_metric` postfix? as all of them are in a `Metrics` struct already.

2022-10-14 17:02 UTC, merged