Salman/private tx events
webb-tools/relayer pull request #293
Opened 2022-11-02 13:23 UTC by salman01zp

## Summary of changes
- [ ] Add tracing events to private transaction requests
- [ ] Add vanachor private transaction test

### Reference issue to close (if applicable)
- Closes #213 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2022-11-03 17:24 UTC, drewstone requested changes
Looks good! Small nitpicks on the naming

2022-11-03 17:24 UTC, drewstone commented on tests/lib/webbRelayer.ts
> +export type SubstrateVanchorProofData = {
```suggestion
export type SubstrateVAnchorProofData = {
```

2022-11-03 17:24 UTC, drewstone commented on tests/lib/webbRelayer.ts
> +export type SubstrateVanchorExtData = {
```suggestion
export type SubstrateVAnchorExtData = {
```

2022-11-03 17:24 UTC, drewstone commented on tests/test/substrate/vanchorPrivateTransaction.test.ts
> +  generateVAnchorNote,
Can you make a task to move some of these tools to the test-utils?

2022-11-04 04:38 UTC, salman01zp commented on tests/test/substrate/vanchorPrivateTransaction.test.ts
> +  generateVAnchorNote,
yes, will do that and update the tests soon.

2022-11-04 14:39 UTC, merged