Substrate event watcher trait
webb-tools/relayer pull request #352
Opened 2023-02-21 12:38 UTC by salman01zp

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-02-22 16:44 UTC, shekohex requested changes

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/lib.rs
> +pub struct DKGEventWatcher;
This should be named the `DKGMetadataWatcher` as the name of the pallet is the dkg-metadata in the repo, but in the code or as exposed by the runtime, it is called `DKG`.

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/proposal_removed_watcher.rs
> +pub struct ProposalRemovedWatcher;
Why do we have a proposal removed watcher? it should be a handler instead.

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/proposal_removed_watcher.rs
> +    }
I guess this old, no?

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/proposal_signed_handler.rs
> +/// It watches for the `ProposalSigned` event and sends the proposal to the signature bridge.
```suggestion
/// A ProposalSignedHandler handles the `ProposalSigned` event and sends the proposal to the configured signature bridges contracts. 
```

2023-02-22 16:44 UTC, shekohex commented on crates/event-watcher-traits/src/substrate/event_watcher.rs
> +                    });
Looks like we should call `handler.can_handle_events(events.clone())` here first, and return early before we call `handle_events_with_retry` method.

2023-02-22 16:44 UTC, shekohex commented on crates/event-watcher-traits/src/substrate/event_watcher.rs
> +    async fn can_handle_event(
the name should be `can_handle_events` instead of `can_handle_event`

2023-02-22 16:44 UTC, shekohex commented on crates/event-watcher-traits/src/substrate/event_watcher.rs
> +    /// Check if events can be handled by handler
```suggestion
    /// Whether any of the events could be handled by the handler
```

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/proposal_signed_handler.rs
> +        }
IMO this redundant. the caller should call `can_handle_events` first. but nonetheless, the `events.find` method will return an empty list of events; so that the loop will never start.

2023-02-22 16:44 UTC, shekohex commented on event-watchers/dkg/src/public_key_changed_handler.rs
> +/// It watches for the DKG Public Key changes and try to update the signature bridge governor.
Comments needs to be updated.

2023-02-23 09:29 UTC, shekohex requested changes

2023-02-23 09:29 UTC, shekohex commented on event-watchers/dkg/src/lib.rs
> +    const PALLET_NAME: &'static str = "DKGMetadata";
The pallet name in the Runtime is called `DKG`, the other smarter way, is to get the name dynamically from the generated code, using `PublicKeySignatureChanged::PALLET` for example.

2023-02-23 12:03 UTC, drewstone approved these changes

2023-02-23 12:17 UTC, merged