Fast sync and merkle root validation
webb-tools/relayer pull request #354
Opened 2023-02-27 11:28 UTC by salman01zp

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-03-06 02:49 UTC, salman01zp commented
There seems to be some issue with the latest protocol-substrate docker image. It fails to form a connection with the node.

2023-03-08 17:30 UTC, shekohex requested changes
LGTM! just few changes and is good to go.

2023-03-08 17:30 UTC, shekohex commented on event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
> +                    tracing::info!("Clear merkle tree...!");
```suggestion
                    tracing::warn!("Clear merkle tree...!");
```

2023-03-08 17:30 UTC, shekohex commented on event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
> +                    tracing::info!("Clear local leaves cache...!");
```suggestion
                    tracing::warn!("Clear local leaves cache...!");
```

2023-03-08 17:30 UTC, shekohex commented on event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
> +                    tracing::info!("Clear last deposit block number...!");
```suggestion
                    tracing::warn!("Clear last deposit block number...!");
```

2023-03-08 17:30 UTC, shekohex commented on event-watchers/evm/src/vanchor/vanchor_leaves_handler.rs
> +                    tracing::info!(
```suggestion
                    tracing::warn!(
```

2023-03-08 17:35 UTC, shekohex approved these changes

2023-03-08 17:36 UTC, merged