WIP: Bridge Registry pallet integration
webb-tools/relayer pull request #355
Opened 2023-03-02 13:34 UTC by Nutomic

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-03-03 10:07 UTC, Nutomic commented on crates/proposal-signing-backends/tests/submit_anchor_update_proposal.rs
> +    watch_events(&mut progress).await;
This is failing with `Runtime error: Other([2, 198, 228, 152, 23, 0, 0, 0])`. If I register the resources manually via Polkadot js admin ui and comment out this code, the test passes.

2023-03-08 17:43 UTC, shekohex commented
fyi, @Nutomic I did change the base branch to be `develop`.

2023-03-15 15:44 UTC, Nutomic commented on services/webb-relayer/src/service.rs
> +                );
I didnt create a separate init method for bridge registry because it would be more trouble than its worth for this little code. Especially with another dkg/mocked selector the match would get very complicated. This does the job fine (unless we want to pass in more parameters).

2023-03-15 15:54 UTC, Nutomic commented on crates/bridge-registry-backends/tests/submit_anchor_update_proposal.rs
> +async fn submit_anchor_update_proposal() {
Not sure if we can execute this test in CI as it requires a running relayer. At least its already checking that the code here compiles.

2023-03-15 15:57 UTC, shekohex requested changes
Looks good so far, a few comments about the terminology

2023-03-15 15:57 UTC, shekohex commented on Cargo.toml
> +webb = { git = "https://github.com/webb-tools/webb-rs.git", rev = "2bbe7b6a4f9", default-features = false }
We will publish the new version of webb-rs with the new changes, so we will hold this PR until we update the runtime of protocol-substrate there too.

cc @salman01zp are there a PR to do that already?

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/src/dkg.rs
> +    async fn resource_to_bridge_id(
Let's be more clear about naming methods, this uses an inner method called `resource_to_bridge_index` so lets use that.

```suggestion
    async fn resource_to_bridge_index(
```

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/src/dkg.rs
> +    ) -> webb_relayer_utils::Result<u32> {
This method should return an `Option<u32>` and if it is `None` that means this bridge does not exist. Using this method right now, as you can see it will return index of `1` which means bridge 1, this resource could not be in that bridge at all, resulting in a bug.

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/src/lib.rs
> +    async fn resource_to_bridge_id(
```suggestion
    async fn resource_to_bridge_index(
```

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/src/lib.rs
> +    /// Retrieves the bridge ID which a given resource is attached to.
```suggestion
    /// Retrieves the bridge index which a given resource is attached to.
```

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/src/lib.rs
> +                    .map(|r| {
Use [`filter_map`](https://doc.rust-lang.org/stable/core/iter/trait.Iterator.html#method.filter_map) instead

2023-03-15 15:57 UTC, shekohex commented on crates/bridge-registry-backends/tests/submit_anchor_update_proposal.rs
> +async fn submit_anchor_update_proposal() {
just add `#[ignore = "requires ...."]` on that.

2023-03-16 09:40 UTC, Nutomic commented on crates/bridge-registry-backends/src/lib.rs
> +                    .map(|r| {
That might be a good idea in some cases but here it requires more code because of explicit if else. Current implementation is simpler.

2023-03-16 09:44 UTC, shekohex commented on crates/bridge-registry-backends/src/lib.rs
> +                    .map(|r| {
Sounds good!

2023-03-16 10:14 UTC, Nutomic commented
Updated for review comments, but now CI is throwing weird internal compiler errors. It passed previously and the changes were very minor. So Im guessing the nightly is broken.

2023-03-16 12:34 UTC, salman01zp commented
Yes latest nightly is failing I am using [nightly-2023-03-12](https://github.com/webb-tools/relayer/pull/371/commits/a55d1bc605902d2e2f72ffb92b8bdcd6e9171a3d#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4eR2) for now

2023-03-16 12:54 UTC, shekohex commented
> Yes latest nightly is failing I am using [nightly-2023-03-12](https://github.com/webb-tools/relayer/pull/371/commits/a55d1bc605902d2e2f72ffb92b8bdcd6e9171a3d#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4eR2) for now

@Nutomic can you start using this and push that so that CI works?

2023-03-21 10:13 UTC, shekohex commented on Cargo.toml
> +webb = { git = "https://github.com/webb-tools/webb-rs.git", rev = "2bbe7b6a4f9", default-features = false }
@Nutomic could you update this and use the new version of webb?

2023-03-21 10:59 UTC, salman01zp commented
we also need to update validation checks [here](https://github.com/webb-tools/relayer/blob/main/services/webb-relayer/src/service.rs#L1202-#L1215) . 
If the relayer is configured with a governance feature enabled, it will validate if linked anchors are provided before starting the governance relaying service

2023-03-21 16:20 UTC, shekohex approved these changes

2023-03-21 16:21 UTC, merged