Substrate governor update
webb-tools/relayer pull request #371
Opened 2023-03-15 10:06 UTC by salman01zp

## Summary of changes
- [ ] Send `nonce+dkg key` to signature bridge to update maintainer
- [ ] Governor update flow test for substrate

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-03-15 10:10 UTC, salman01zp commented
We will need to force set maintainer nonce too along with maintainer/governor. I have drafted a PR for it [here](https://github.com/webb-tools/protocol-substrate/pull/305).

2023-03-15 10:11 UTC, salman01zp commented
will need to update `protocol-substrate-types` and rust bindings in `webb-rs`.

2023-03-15 17:17 UTC, shekohex commented
> We will need to force set maintainer nonce too along with maintainer/governor. I have drafted a PR for it [here](https://github.com/webb-tools/protocol-substrate/pull/305).

This PR is now merged!

2023-03-15 17:45 UTC, shekohex commented
44

> will need to update `protocol-substrate-types` and rust bindings in `webb-rs`.

the PR is up here https://github.com/webb-tools/webb-rs/pull/125

2023-03-20 12:07 UTC, drewstone reviewed
Looks good, double check spacing,need more reviews but looks good otherwise.

2023-03-20 12:07 UTC, drewstone commented on tests/lib/substrateNodeBase.ts
> +            // Other, CannotLookup, BadOrigin, no extra info
Spacing off?

2023-03-20 12:07 UTC, drewstone commented on tests/lib/substrateNodeBase.ts
> +            // for module errors, we have the section indexed, lookup
Spacing off?

2023-03-20 12:35 UTC, shekohex reviewed
Looks good, try to run `yarn format` inside the tests to format all typescript files.

2023-03-21 09:17 UTC, shekohex approved these changes

2023-03-21 09:17 UTC, merged

2023-03-21 09:29 UTC, drewstone requested changes

2023-03-21 09:29 UTC, drewstone commented on crates/event-watcher-traits/src/evm/bridge_watcher.rs
> +            let typed_chain_id =
Can the other variable be deleted?

2023-03-21 10:22 UTC, Nutomic commented
It seems that this change broke integration tests, this is what I get on develop:
```
yarn && yarn test

TSError: ⨯ Unable to compile TypeScript:
test/evm/evmToSubstrateTransaction.test.ts:298:78 - error TS2554: Expected 7 arguments, but got 8.

298     await vanchor1.transact([], [depositUtxo], 0, 0, '0', '0', tokenAddress, {
~
299       [typedSourceChainId]: leaves,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
300     });
~~~~~
test/evm/evmToSubstrateTransaction.test.ts:331:7 - error TS2345: Argument of type 'import("/home/felix/workspace/webb/relayer/tests/node_modules/@webb-tools/test-utils/node_modules/@webb-tools/anchors/lib/VAnchor").VAnchor' is not assignable to parameter of type 'import("/home/felix/workspace/webb/relayer/tests/node_modules/@webb-tools/anchors/lib/VAnchor").VAnchor'.
Type 'VAnchor' is missing the following properties from type 'VAnchor': leafCreatedAtBlock, updateTreeOrForestState, generateProof, register, and 14 more.

331       vanchor1,
~~~~~~~~

at createTSError (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/index.ts:863:19)
at getOutput (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/index.ts:1077:36)
at Object.compile (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/index.ts:1433:41)
at transformSource (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/esm.ts:400:37)
at /home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/esm.ts:278:53
at async addShortCircuitFlag (/home/felix/workspace/webb/relayer/tests/node_modules/ts-node/src/esm.ts:409:15)
at async nextLoad (node:internal/modules/esm/loader:163:22)
at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
at async link (node:internal/modules/esm/module_job:67:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2023-03-21 11:09 UTC, salman01zp commented
did you try yarn install ?

2023-03-21 11:16 UTC, Nutomic commented
Just tried it, same errors as before.

2023-03-21 11:34 UTC, salman01zp commented
Clearning node modules, cache, and reinstalling should fix it.