Fees for substrate
webb-tools/relayer pull request #375
Opened 2023-03-21 13:48 UTC by Nutomic

## Summary of changes
- Add fee and refund logic for substrate
- Update test instructions to include tangle setup
- Update fee endpoints
- Update test case `should withdraw using private transaction` to use fee and refund

## Note
We have updated the fee endpoint to support requests for  substrate and evm based chains, following are the new points
- EVM:
```
  /api/v1/fee_info/evm/:chain_id/:vanchor/:gas_amount
```
-  Substrate
```
 /api/v1/fee_info/substrate/:chain_id/:partialFee
```

### Reference issue to close (if applicable)
- Closes #364 
- Closes #503 
-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-03-24 11:31 UTC, Nutomic commented on crates/tx-relay/src/evm/fees.rs
> +    let max_refund = min(relayer_balance, max_refund);
Noticed that this check was previously missing in evm fee code, so a client might request refund that is higher than relayer balance.

2023-03-24 11:34 UTC, Nutomic commented on crates/tx-relay/src/substrate/fees.rs
> +}
Very simple logic because its using hardcoded values. For this reason I also havent implemented any caching.

2023-03-24 11:35 UTC, Nutomic commented on crates/tx-relay/src/substrate/vanchor.rs
>      );
Not sure how to send the refund in substrate.

2023-03-24 11:35 UTC, Nutomic commented on crates/tx-relay/src/substrate/vanchor.rs
> +    //let balance = client.storage().at(None).await.unwrap().
I cant manage to get the relayer wallet balance here.

2023-03-28 12:57 UTC, shekohex commented on crates/tx-relay/src/substrate/vanchor.rs
>      );
it is in the `ext_data_elements` already set by the user, and the pallet automatically handles the native token transfer for you.

2023-03-28 12:57 UTC, shekohex commented on crates/tx-relay/src/substrate/vanchor.rs
> +    //let balance = client.storage().at(None).await.unwrap().
I guess we resolved that in our conversation on Slack, no?

2023-03-28 13:29 UTC, Nutomic commented on crates/tx-relay/src/substrate/vanchor.rs
> +    //let balance = client.storage().at(None).await.unwrap().
No this is still not working, its returning None. I pushed my latest code just now.

2023-04-14 13:02 UTC, Nutomic commented
Currently waiting for this PR to make webb.js dependencies work with Node 18.

https://github.com/webb-tools/webb.js/pull/311

2023-04-28 17:58 UTC, drewstone commented
This can be updated now afaik

2023-04-28 19:04 UTC, shekohex commented
> This can be updated now afaik

Updated and fixed the merge conflicts too.

2023-05-08 14:13 UTC, Nutomic commented
I pushed the changes made with @shekohex to fix fee calculation. Now its still failing with the error `Error: the string "Error while watching Tx: Runtime error: Module(ModuleError { pallet: \"VAnchorBn254\", error: \"InvalidExtData\", description: [], error_data: ModuleErrorData { pallet_index: 41, error: [6, 0, 0, 0] } })" was thrown, throw an Error :)`. Most likely the problem is somewhere in `vanchorWithdraw()` inside `vanchorPrivateTransaction.test.ts`. That file had some hardcoded values before which I had to replace, and most likely there is something wrong.

2023-05-09 16:08 UTC, drewstone commented
What's the status of this @Nutomic ?

2023-05-10 13:45 UTC, Nutomic commented
I cleaned up the Rust code now, adding error handling, fixing todos and making clippy pass. So only thing left is fixing the tests.

2023-05-12 08:06 UTC, Nutomic commented on crates/relayer-handler-utils/src/lib.rs
> +type A = WebbI256; // Substrate signed amount type
Is this correct? Based on the original code it should be i128. Although thats causing errors so we might have to create `WebbI128`.

2023-05-12 08:52 UTC, shekohex commented on crates/relayer-handler-utils/src/lib.rs
> +type A = WebbI256; // Substrate signed amount type
Yes please, create a custom type here like `WebbI128`

2023-05-12 09:04 UTC, shekohex requested changes
Looks good! just few things needs that needs more clean-ups

2023-05-12 09:04 UTC, shekohex commented on services/webb-relayer/src/service/evm.rs
> +            get(handle_evm_fee_info),
This a breaking change, so we may want to outline this into the PR overview?

2023-05-12 09:04 UTC, shekohex commented on services/webb-relayer/src/service/evm.rs
> +            get(handle_evm_fee_info),
Will be useful for the dApp team to do these updates too.

2023-05-12 09:05 UTC, shekohex commented on services/webb-relayer/src/service/evm.rs
> +            get(handle_evm_fee_info),
cc @AtelyPham @dutterbutter

2023-05-12 09:40 UTC, Nutomic commented on services/webb-relayer/src/service/evm.rs
> +            get(handle_evm_fee_info),
I mentioned it in the summary of changes, should I add anything there?

2023-05-12 09:42 UTC, salman01zp commented on crates/tx-relay/src/evm/vanchor.rs
> -
This check was removed cc: @Nutomic  adding it back

2023-05-12 09:43 UTC, Nutomic commented on crates/tx-relay/src/evm/vanchor.rs
> -
Line 159 (because fee_info was changed to check the balance when calculating max_refund).

2023-05-12 09:45 UTC, salman01zp commented on crates/tx-relay/src/evm/vanchor.rs
> -
I see..

2023-05-12 09:45 UTC, shekohex commented on services/webb-relayer/src/service/evm.rs
> +            get(handle_evm_fee_info),
No, all is good.

2023-05-12 09:46 UTC, shekohex commented on crates/tx-relay/src/evm/vanchor.rs
> -
Relayer balance could change from the moment where we cached the fees and when we executing the actual tx.

2023-05-12 09:53 UTC, Nutomic commented on crates/tx-relay/src/evm/vanchor.rs
> -
Okay will add code to recheck the balance when using cached value.

2023-05-12 11:00 UTC, shekohex approved these changes
Awesome work everyone, LGTM!

2023-05-12 11:03 UTC, merged