Add `api/v1/info` endpoint for relayer info.
webb-tools/relayer pull request #4
Opened 2021-07-15 19:28 UTC by shekohex

This is the following PR after #3 landed in `main`.
this PR adds the following HTTP endpoint: GET `api/v1/info`
this API Endpoint will respond back with relayer configuration.

**Example**:
```json

{

    "substrate": {
        "webb": { },
        "edgeware": null,
        "hedgeware": null,
        "beresheet": null
    },
    "evm": {
        "webb": null,
        "edgeware": null,
        "ganache": {
            "withdrewFee": "0x5",
            "withdrewGaslimit": "0x350000",
            "account": "0x7b1afe2745533d852d6fd5a677f14c074210d896"
        },
        "hedgeware": null,
        "beresheet": {
            "withdrewFee": "0x5",
            "withdrewGaslimit": "0x350000",
            "account": "0x48d41e139d3133f1879ce5080b9c2cb4878332c2"
        },
        "harmony": {
            "withdrewFee": "0x5",
            "withdrewGaslimit": "0x350000",
            "account": "0x48d41e139d3133f1879ce5080b9c2cb4878332c2"
        }
    }

}

```

**Notes**:

* if the network is `null` that obviously means this network is not supported or not configured correctly for this relayer.
* The `account` is derived from the account's private key, this would be used during zkp as the value of the relayer account.

2021-07-15 20:29 UTC, nepoche commented
Are there any updates that need to be made to the relayer's config.toml? Using postman, I attempted a GET request for `http://localhost:9955/api/v1/info`, but errored out.

2021-07-15 20:34 UTC, shekohex commented
Can you please share the error? also, can you try to open the url in the browser too?

2021-07-15 20:47 UTC, nepoche commented
Here are some screenshots of the setup and error:
<img width="700" alt="Screen Shot 2021-07-15 at 4 45 23 PM" src="https://user-images.githubusercontent.com/16654909/125855301-14cc63d8-7ffc-4ded-bbed-5719995c2a55.png">
<img width="1241" alt="Screen Shot 2021-07-15 at 4 45 58 PM" src="https://user-images.githubusercontent.com/16654909/125855303-f86cf92c-24b0-48d7-96db-9f4e78d354c3.png">
<img width="1208" alt="Screen Shot 2021-07-15 at 4 46 32 PM" src="https://user-images.githubusercontent.com/16654909/125855305-12452e70-c30b-4c3a-9306-199865b30dd5.png">

2021-07-16 18:01 UTC, drewstone requested changes
Looks great!

2021-07-16 18:01 UTC, drewstone commented on src/handler.rs
> +    update_account_for!(webb, evm::Webb);
cool macro! can you document it a bit more?

2021-07-17 10:49 UTC, shekohex commented on src/handler.rs
> +    update_account_for!(webb, evm::Webb);
Done.

2021-07-17 10:52 UTC, shekohex commented on tests/main.ts
> +  const relayerInfoRes = await fetch('http://localhost:9955/api/v1/info');
@nepoche I added a way to query relayer information during the tests here, so we at least make sure it works

2021-07-17 10:52 UTC, shekohex commented on tests/main.ts
> +  console.log({ relayerChainInfo });
and reading the `withdrewFee` is easy from here.

2021-07-19 15:40 UTC, nepoche commented on src/chains.rs
> +        Harmony => {
From what I can tell, the shards operate as separate EVMs. So if we are deploying on multiple shards, then we should define separate chains.

2021-07-26 14:10 UTC, merged