Semar/masp batch deposits
webb-tools/relayer pull request #453
Opened 2023-04-10 20:21 UTC by semaraugusto

## Summary of changes
- Adds proof generation for the batch deposit functionality on the MASP
- Adds `masp_leaves_handler`, 
- Adds `masp_proxy_handler`

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/relayer/issues/438
- Closes https://github.com/webb-tools/relayer/issues/434
- Closes https://github.com/webb-tools/relayer/issues/437 (proof doesnt depend on which tree we're using)

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-04-12 13:14 UTC, salman01zp commented
Can you also link SPEC for MASP Relayer Integration to this PR..?

2023-04-12 14:37 UTC, semaraugusto commented
base relayer integrations spec: https://www.notion.so/MASP-Relayer-Integration-8d4f6e4c8e124dc1b87bac4766783bd5

batch deposit specific spec: https://www.notion.so/hicommonwealth/Batched-Reward-Tree-Processing-7d51b34188584288af9266e7f2a06542

2023-04-12 15:48 UTC, drewstone requested changes

2023-04-12 15:48 UTC, drewstone commented on crates/relayer-config/src/evm/mod.rs
> +    pub proposal_signing_backend: Option<ProposalSigningBackendConfig>,
Is this needed or used anywhere on the proxy config? I recommend starting with only the things we use so these objects don't get clogged.

2023-04-12 15:48 UTC, drewstone commented on event-watchers/evm/src/masp/masp_generate_batch_deposit_proof.rs
> +        // pre-generated inputs
Please instruct how to generate these pre-generated inputs too. All pre-generated fixture tests should be reproducible from the first step.

2023-04-12 15:48 UTC, drewstone commented on event-watchers/evm/src/masp/masp_leaves_handler.rs
> +                if event_data.leaf_index.as_u32() % 2 == 0 {
If we are requiring the local MT for the relayer to be in sync, wouldn't this prevent that if the leaf index is even? Should this be removed?

2023-04-12 15:48 UTC, drewstone commented on event-watchers/evm/src/masp/masp_leaves_handler.rs
> +                if event_data.leaf_index.as_u32() % 2 == 0 {
Is this function copied from the VAnchor leaf watcher? If so, are we duplicating code that can otherwise be consolidated?

2023-04-13 16:54 UTC, drewstone requested changes

2023-04-13 16:54 UTC, drewstone commented on event-watchers/evm/src/masp/masp_generate_batch_deposit_proof.rs
> +use ark_bn254::{Bn254, Fr};
Thoughts on moving files like these into a separate crate? Something dedicated to all our proof generation needs?

2023-04-20 15:04 UTC, closed without merging