add a delegate to receive rewards
webb-tools/relayer pull request #46
Opened 2021-11-17 17:36 UTC by jim4067

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Webb Relayer does not have the ability to to specify another address for rewards. added a way to specify a `reward-address` instead of default account for fee rewards

## What is the new behavior?
Now we are able to specify an address that is different from the one submitting the transaction for fee rewards

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2021-11-17 21:54 UTC, shekohex commented on config/ethereum/ganache.toml
> +reward-address = "0x1111111111111111111111111111111111111111"
```suggestion
beneficiary = "0x1111111111111111111111111111111111111111"
```

2021-11-17 21:55 UTC, shekohex commented on src/config.rs
> +
```suggestion
```

2021-11-17 21:55 UTC, shekohex commented on src/config.rs
> +        Ok(config) => dbg!(postloading_process(config)),
```suggestion
        Ok(config) => postloading_process(config),
```

2021-11-17 21:56 UTC, shekohex requested changes
Just a few changes and this would be ready to go.

Also, @jim4067 could you also update the docs for the README file?

2021-11-18 07:04 UTC, jim4067 commented on src/config.rs
> +        Ok(config) => dbg!(postloading_process(config)),
I removed the dbg! macro yesterday.

2021-11-18 07:26 UTC, jim4067 commented on src/config.rs
> +
done

2021-11-18 07:27 UTC, jim4067 commented
no problem @shekohex

2021-11-18 14:43 UTC, nepoche requested changes

2021-11-18 14:43 UTC, nepoche commented on config/ethereum/rinkeby.toml
> +beneficiary = "0x2222222222222222222222222222222222222222"
```suggestion

```

2021-11-18 14:43 UTC, nepoche commented on config/harmony/testnet1.toml
> +#account address for fee rewards (other than the one which is submitting the transaction)
```suggestion

```

2021-11-18 15:06 UTC, shekohex approved these changes

2021-11-18 15:09 UTC, shekohex commented
There is something wrong with the checks, @jim4067 could you try fixing these falling tests?

2021-11-18 17:48 UTC, nepoche commented
Need to coordinate a merge / updates with dapp integrations

2021-11-19 21:39 UTC, merged