Use transaction queue for DKG/Substrate (fixes #450)
webb-tools/relayer pull request #461
Opened 2023-04-14 11:21 UTC by Nutomic

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-04-14 12:23 UTC, Nutomic commented on crates/proposal-signing-backends/src/dkg.rs
> -        }
There is no progress returned so this code doesnt work anymore. I assume similar logs are already written somewhere in the tx queue.

2023-04-14 12:39 UTC, shekohex requested changes
Not entirely there yet, but looks a like a good start.

2023-04-14 12:39 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +        enqueue_transaction(execute_proposal_call, self.store.as_ref())?;
Well first of all, this does not sound right to me, the original code used the `acknowledge_proposal` call, not `execute_proposal` call, which are two different extrinsic from two different pallets. 

Besides, there is no need for signing anything, why you used the `self.pair.sign` call here? the TxQueue is responsible for signing proposals.

2023-04-14 12:39 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +    Ok(())
There is no need for creating a function here, each transaction has to be constructed on its own, you are creating a function to enqueue the wrong transaction, not even the one originally in the code. Please update the code to use the original transaction.

2023-04-17 09:10 UTC, Nutomic commented on crates/proposal-signing-backends/src/dkg.rs
> +    Ok(())
Okay removed this.

2023-04-17 09:15 UTC, Nutomic commented on crates/proposal-signing-backends/src/dkg.rs
> +        enqueue_transaction(execute_proposal_call, self.store.as_ref())?;
It wasnt clear to me which extrinsic it is using here, fixed that. The queue docs also dont mention anything about signing, so I assumed that it has to be passed exactly like in signature bridge watcher. Should be fixed now.

2023-04-17 09:16 UTC, Nutomic commented on crates/proposal-signing-backends/src/dkg.rs
> +        _metrics: Arc<Mutex<metric::Metrics>>,
Metrics are unused now, not sure if we should use it for something else or remove the param.

2023-04-17 12:39 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +        _metrics: Arc<Mutex<metric::Metrics>>,
We would use it in the future, I assume by adding more metrics to the system.

2023-04-20 10:12 UTC, shekohex requested changes
Looks good! Almost complete, but not entirely right, yet! Left some comments.

2023-04-20 10:12 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +        };
This call is wrong, first of all the pallet name is `DKGProposals` as you can find it here in the runtime:
https://docs.rs/webb/0.5.21/src/webb/substrate/dkg_runtime.rs.html#14

Another this is the parameters does not look right to me, this call takes 4 args (nonce, src_chain_id, resource_id, proposal_bytes)
Here is a suggested fix:
```suggestion
        let execute_proposal_tx = WebbDynamicTxPayload {
            pallet_name: Cow::Borrowed("DKGProposals"),
            call_name: Cow::Borrowed("acknowledge_proposal"),
            fields: vec![
                Value::u128(u128::from(nonce)),
                Value::u128(u128::from(self.typed_chain_id.chain_id())),
                Value::from_bytes(ResourceId(resource_id.into_bytes()).encode()),
                Value::from_bytes(BoundedVec(proposal.to_vec()).encode()),
            ],
        };
```

2023-04-20 10:12 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +            make_execute_proposal_key(data_hash),
function name here is misleading, there is not execute proposal in the process, I would suggest renaming it to something like:
```suggestion
            make_ acknowledge_proposal_key(data_hash),
```

2023-04-20 10:12 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
> +}
Same as above, we could better name this function:
```suggestion
pub fn make_ acknowledge_proposal_key(data_hash: [u8; 32]) -> [u8; 64] {
    let mut result = [0u8; 64];
    // make sure that this byte array is 32 bytes.
    let prefix = b"acknowledge_proposal_fixed_key_";
    result[0..32].copy_from_slice(prefix);
    result[32..64].copy_from_slice(&data_hash);
    result
}
```

2023-04-20 10:12 UTC, shekohex commented on event-watchers/substrate/src/signature_bridge_watcher.rs
> -}
we should revert this change and bring this function again back.

2023-04-20 12:49 UTC, Nutomic commented on event-watchers/substrate/src/signature_bridge_watcher.rs
> -}
I moved it to crates/proposal-signing-backends/src/dkg.rs above because I thought the code can be shared, but apparently thats not the case.

2023-04-20 12:54 UTC, Nutomic commented
Updated with these suggestions.

2023-04-20 13:03 UTC, shekohex approved these changes
LGTM! 👍

I will be auto-merged once all the CI checks passes.

2023-04-20 13:19 UTC, Nutomic commented
This test below keeps failing randomly, have to restart to fix it.

```
   1) Vanchor Transaction relayer
       number of deposits made should be equal to number of leaves in cache:

      AssertionError: expected [ …(10) ] to deeply equal [ …(10) ]
      + expected - actual
```

2023-04-20 13:34 UTC, shekohex commented
> This test below keeps failing randomly, have to restart to fix it.
> 
> ```
>    1) Vanchor Transaction relayer
>        number of deposits made should be equal to number of leaves in cache:
> 
>       AssertionError: expected [ …(10) ] to deeply equal [ …(10) ]
>       + expected - actual
> ```

Would you like to open a Task to look into this issue?

2023-04-20 14:42 UTC, merged