add proof-generation crate for masp integration
webb-tools/relayer pull request #467
Opened 2023-04-18 13:59 UTC by semaraugusto

## Summary of changes
- Adds `MaspDelegatedProver` for generating proof in behalf of the user
- Adds `MaspBatchProver` for generating merkle tree batch insertion proofs (works for depositTree, UnspentTree and SpentTree bc the prover doesn't depend on the merkle-tree itself) 
- Adds tests for both provers by providing pre-generated proof inputs

Batch Prover spec
https://www.notion.so/hicommonwealth/Batched-deposit-processing-8a9cbea47acc448cb1076fac86161fd0

Delegated prover spec
https://www.notion.so/hicommonwealth/Delegatable-proof-generation-c8d64aa16957407496e5c706130346d7

### Reference issue to close (if applicable)
- Closes  https://github.com/webb-tools/relayer/issues/441
- Closes https://github.com/webb-tools/relayer/issues/433
- Closes https://github.com/webb-tools/relayer/issues/437
-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-04-18 20:35 UTC, drewstone requested changes
LG

2023-04-18 20:36 UTC, drewstone commented on crates/circom-proving/src/lib.rs
> +/// Verifies a given RLN proof
Comment need to be updated.

2023-04-20 10:35 UTC, shekohex commented
It would be good to have a meeting or a call about this PR and the overall task so I could understand better and review the PR with the correct assumptions.

2023-04-20 17:57 UTC, shekohex reviewed
Looks good to me! 
It needs a little bit of clean ups but we can do that later on new PRs.

2023-04-24 12:43 UTC, merged