Rework resource metrics
webb-tools/relayer pull request #472
Opened 2023-04-20 10:29 UTC by Nutomic

## Summary of changes
- Previous Grafana dashboard was broken for some reason, had to recreate it from scratch
- Dashboard now includes resource metrics

### Reference issue to close (if applicable)
- Closes #387

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-04-20 10:32 UTC, Nutomic commented on Cargo.toml
> +webb-proposals = { git = "https://github.com/webb-tools/webb-rs", branch = "felix/display-resource-id", default-features = false, features = ["scale"] }
This is to include the Display trait for ResourceId from https://github.com/webb-tools/webb-rs/pull/133. However it fails to compile, dont know why:

```
error: cannot find macro `thread_local` in this scope
--> /home/felix/.cargo/git/checkouts/substrate-7e08433d4c370a21/1837f42/primitives/externalities/src/scope_limited.rs:22:1
|
22 | environmental::environmental!(ext: trait Externalities);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `thread_local` is in scope, but it is an attribute: `#[thread_local]`
= note: this error originates in the macro `$crate::thread_local_impl` which comes from the expansion of the macro `environmental::environmental` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find value `GLOBAL` in this scope
--> /home/felix/.cargo/git/checkouts/substrate-7e08433d4c370a21/1837f42/primitives/externalities/src/scope_limited.rs:22:1
|
22 | environmental::environmental!(ext: trait Externalities);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
|
= note: this error originates in the macro `$crate::environmental` which comes from the expansion of the macro `environmental::environmental` (in Nightlybuilds, run with -Z macro-backtrace for more info)
```

We could leave this out for now and use the hex representation of resource for metrics until it is fixed.

2023-04-20 10:33 UTC, Nutomic commented on crates/relayer-utils/src/metric.rs
> +            labels!("resource_id" => &resource_name)
https://prometheus.io/docs/practices/naming/#labels

2023-04-20 10:53 UTC, shekohex requested changes
Looks good! left some comments.

2023-04-20 10:53 UTC, shekohex commented on crates/relayer-utils/src/metric.rs
> +            labels!("resource_id" => &resource_name)
I like that idea of using labels here for resource_ids!
what if we could even go further by making it more readable by having the following:
1. the API stays the same, it operates over the resource Ids, however, we could have many labels like
`chain_type` (`evm`, `substrate`, ..etc) and `chain_id` which is another label that represent the chainID.
`target_system_type` (`contract`, `tree_id`, ..etc) and `target_system_value` (`0xAe91...e28D`, 4, ..etc)

What do you think? we can now filter by labels like `evm` and chain id `5` with contract and its value `0xAe91...e28D`

2023-04-20 10:53 UTC, shekohex commented on crates/relayer-utils/src/metric.rs
> +        .expect("create gauge for account balance");
Here is the thing, the account balance is to tied to a single resoruce id, it is actually tied to a system or a chain, so we can move this up on its own `HashMap<TypedChainId, AccountBalanceMetric>` for example.

2023-04-20 13:27 UTC, Nutomic commented on crates/relayer-utils/src/metric.rs
> +            labels!("resource_id" => &resource_name)
I will give this a try. Not entirely sure how it will work with Grafana if there are for example identical chain_ids on two different chains. But it can probably work somehow.

2023-04-24 14:13 UTC, Nutomic commented on crates/tx-relay/src/substrate/mod.rs
> +}
I didnt find any builtin function in subxt for this.

2023-04-24 14:17 UTC, shekohex commented on crates/tx-relay/src/substrate/mod.rs
> +}
We can use a similar approach with the one we did here #471, I guess it is okay to use ethers utils here.

2023-04-24 14:29 UTC, Nutomic commented
This is finished. Tests keep timing out in CI but they are passing locally.

2023-04-24 22:20 UTC, merged