Handle substrate node disconnection
webb-tools/relayer pull request #522
Opened 2023-05-25 13:56 UTC by salman01zp

## Summary of changes
-  If the substrate node connection is closed, drop the client and retry connecting with ExponentialBackoff time in event watcher trait.

```rust

let backoff = backoff::ExponentialBackoff {
    max_elapsed_time: None,
    ..Default::default()
};
let metrics_clone = metrics.clone();
let task = || async {
    let maybe_client = ctx
        .substrate_provider::<RuntimeConfig>(&chain_id.to_string())
        .await;
    let client = match maybe_client {
        Ok(client) => client,
        Err(err) => {
            tracing::error!(
                "Failed to connect with substrate client for chain_id: {}, retrying...!",
                chain_id
            );
            return Err(backoff::Error::transient(err));
        }
    };
    let client = Arc::new(client);
    
    
    // handler events
    
    tracing::trace!("Found #{} events", events.len());
    // wraps each handler future in a retry logic, that will retry the handler
    // if it fails, up to `MAX_RETRY_COUNT`, after this it will ignore that event for
    // that specific handler.
    let tasks = handlers.iter().map(|handler| {
        // a constant backoff with maximum retry count is used here.
        let backoff = retry::ConstantWithMaxRetryCount::new(
            Duration::from_millis(100),
            MAX_RETRY_COUNT,
        );
        handler.handle_events_with_retry(
            store.clone(),
            client.clone(),
            (events.clone(), dest_block),
            backoff,
            metrics_clone.clone(),
        )
    });
    let result = futures::future::join_all(tasks).await;

```

### Reference issue to close (if applicable)
- Closes #495

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2023-05-25 16:25 UTC, drewstone approved these changes
LGTM

2023-05-25 16:27 UTC, shekohex requested changes

2023-05-25 16:27 UTC, shekohex commented on crates/event-watcher-traits/Cargo.toml
> +jsonrpsee-ws-client = "0.18.1"
I think we do not need this anymore, no?

2023-05-26 06:56 UTC, shekohex approved these changes

2023-05-26 06:56 UTC, merged