Drew/substrate mixer relay
webb-tools/relayer pull request #59
Opened 2021-12-28 20:29 UTC by drewstone

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
This adds the transaction relay functionality for Webb Protocol Substrate-based mixers.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A
#57 

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

2021-12-29 11:33 UTC, shekohex requested changes
I left a few comments here and there, also pushed some changes too, that would help to progress this PR.

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub proof: Vec<u8>,
Consider using `Bytes` instead of just `Vec<u8>` this would allow the frontend to send it as Hex or Uint8List (a la Byte Buffer).

```suggestion
    pub proof: Bytes,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub root: Element,
The type `Element` will not work here, as it does not implement serde traits.

Prefer the use of `H256` it will give you the exact 32 bytes.
```suggestion
    pub root: H256,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub nullifier_hash: Element,
Same as `root`, use `H256`
```suggestion
    pub nullifier_hash: H256,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub recipient: AccountData,
This one is a bit tricky here, the way we send it to the verifier on the withdraw is that we use custom encoders to make the `AccountId` into a 32 bytes `Element`. so again you should make it `H256` so the client has to format it, or better use `subxt::sp_core::crypto::AccountId32`
```suggestion
    pub recipient: subxt::sp_core::crypto::AccountId32,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub relayer: AccountData,
Same as `recipient` above:
```suggestion
    pub relayer: subxt::sp_core::crypto::AccountId32,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub fee: u128,
prefer `U256` over the normal `u128` as it can take bigger numbers plus it can be sent as hex, making life easier when working from the front-end.
```suggestion
    pub fee: U256,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +    pub refund: u128,
```suggestion
    pub refund: U256,
```

2021-12-29 11:33 UTC, shekohex commented on src/handler.rs
> +            .to_runtime_api::<RuntimeApi<DefaultConfig>>();
Try this one is better, as in the future we maybe cache all these clients instead of open a new connection everytime: 
```suggestion
        let client = ctx.substrate_provider::<DefaultConfig>(&requested_chain).await?;
        let api = client.to_runtime_api::<RuntimeApi<DefaultConfig>>();
```

2021-12-29 11:33 UTC, shekohex commented on tests/proofUtils.ts
> +}
Could you explain what is this function has to do with the substrate? as in it uses ethers here!

2021-12-29 11:33 UTC, shekohex commented on tests/integration_tests/substrate/mixerTests.ts
> +  describe('Sunny day Tornado Relayed transaction', function () {
```suggestion
  describe('Sunny day Mixer Relayed transaction', function () {
```

2021-12-29 14:12 UTC, drewstone commented on src/handler.rs
> +    pub fee: u128,
But the balance on chain is a u128?

2021-12-29 14:13 UTC, drewstone commented on tests/proofUtils.ts
> +}
Yep, this is unfinished atm.

2021-12-29 14:41 UTC, shekohex commented on src/handler.rs
> +    pub fee: u128,
I guess you have to think about how you do send it to the withdraw, if it is u128 then yes, it is all good, if it is a 32bytes array, then we need to change it to that.

2022-01-05 16:50 UTC, shekohex approved these changes

2022-01-06 15:00 UTC, merged