Update relayer with latest tangle-runtime
webb-tools/relayer pull request #600
Opened 2024-01-24 17:36 UTC by salman01zp

## Summary of changes
- 

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

2024-01-24 18:50 UTC, drewstone commented on crates/proposal-signing-backends/src/dkg.rs
>          // all is good!
Let's remove comments like this @salman01zp too

2024-01-29 11:41 UTC, shekohex requested changes
Looks good, just update the code comments to make it match what the code is actually doing.

2024-01-29 11:41 UTC, shekohex commented on crates/proposal-signing-backends/src/dkg.rs
>  /// A ProposalSigningBackend that uses the DKG System for Signing Proposals.
Update comments
```suggestion
/// A ProposalSigningBackend that uses the Signing Rules Contract for Signing Proposals.
```

2024-01-29 11:41 UTC, shekohex commented on services/webb-relayer/src/service/tangle.rs
> +pub fn start_job_result_watcher(
Comments.

2024-01-29 15:33 UTC, shekohex approved these changes

2024-01-29 16:02 UTC, merged